### ISSUE TITLE
Implement a "Clear Cache" button in the client launcher

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop-launcher#118]
Many users ask for a quick way of clearing the application's cache without having to reinstall everything.

The "Clear Cache" behaviour should accomplish the same we accomplish by opening the browser's dev tools -> application -> Clear Site Data, so it would go in the launcher itself.

When the launcher is uninstalled there is a checkbox to delete cached data, the "clear cache" button should also delete that data.

### Acceptance Criteria
- [ ] Have a working "clear cache" button in the launcher

**Comment by aixaCode** [comment]
Closing, not part of the scope
