### ISSUE TITLE
Unsupported OS: linux

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/explorer-desktop-launcher#99]
Hi, not sure if a bug or current limitation, but when running `Decentraland.AppImage` on Linux it outputs the following warning on the terminal: `Unsupported OS: linux`, and that is all it does.

Can't remember the exact release when this started to happen, but was around the Pride Month event

**Comment by EibrielInv** [comment]
Took a look into the code, and to allow the launcher to run on Linux seems fairly easy. It fails when the function `getAppBasePath` returns a relative path.

Adding `linux` on the line https://github.com/decentraland/explorer-desktop-launcher/blob/7a27ede36b816ef3f070893cca8a1328d51941b8/electron/helpers.ts#L64

Adding
```
else if (process.platform === 'linux') {
    return `/some/absolute/path`
}
```
at https://github.com/decentraland/explorer-desktop-launcher/blob/7a27ede36b816ef3f070893cca8a1328d51941b8/electron/helpers.ts#L73

Not sure what is the intended path for linux. Something like `/home/${process.env.USER}/.config/${applicationFolderName}/` ?

**Comment by Kinerius** [comment]
Hey @EibrielInv feel free to open a PR if you find out how this should be configured, I think no one on the explorer team works with Linux and adding support for it hasn't been that much of a priority. 

You can also try and use `app.getPath('userData')` to see if that also works
